name: run main.py

on: 
  schedule:
    - cron: '2 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        user: actions/checkout@v2

      - name: setup python
        user: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: execute py script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update logs" --allow-empty)

      - name: push changes
        user: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main